name: "[builder] CI for releases"

on:
  repository_dispatch:
    types: build
  release:
    types: [published]
  schedule:
    # * is a special character in YAML so you have to quote this string
    # UTC 17:00 -> CST (China) 1:00, see https://datetime360.com/cn/utc-cst-china-time/
    - cron: '0 17 * * *'
  watch:
    types: [started]
  push:
    branches:
      - master
      - develop
    paths:
      - "rootfs/**"
      - "Dockerfile"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Docker Image 构建环境
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # https://github.com/docker/metadata-action
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/rclonebrowser
          tags: |
            latest
            type=schedule,pattern=latest-{{date 'YYYY-MM-DD'}}
            type=semver,pattern={{raw}}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

          
      # Build and push
      - name: Build dockerfile
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          # platforms: linux/amd64
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          
